springdoc:
  api-docs:
    path: /api-documentation

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:algo_space}
    username: ${MYSQL_USERNAME:algo_space}
    password: ${MYSQL_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          import_files: sql/tasks.sql,sql/hints.sql,sql/tests.sql,sql/tasks_available_languages.sql,sql/templates.sql
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

logging:
  level:
    root: info
    zpi.algospace: debug

docker:
  host: ${DOCKER_HOST:tcp://172.17.0.1:2375}
  network: ${DOCKER_NETWORK:bridge}
worker:
  imageName: ${WORKER_IMAGE:algo-space-worker:1.0}
allowed:
  origin: ${FRONTEND_IP:http://localhost:3000}
security:
  jwt:
    secretKey: 'VERYsecretKeyVERYsecretKeyVERYsecretKeyVERYsecretKeyVERYsecretKeyVERYsecretKeyVERYsecretKeyVERYsecretKey'
    tokenPrefix: 'Bearer '
    minutesToTokenExpiration: '180'
