springdoc:
  api-docs:
    path: /api-documentation
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: algo-space
    password: 12345
  h2:
    console:
      enabled: true