springdoc:
  api-docs:
    path: /api-documentation
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:algo_space}
    username: ${MYSQL_USERNAME:algo_space}
    password: ${MYSQL_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files: sql/tasks.sql,sql/hints.sql,sql/tests.sql,sql/tasks_available_languages.sql
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
logging:
  level:
    root: info
    zpi.algospace: debug
    org.apache.kafka: warn
docker:
  host: ${DOCKER_HOST:host.docker.internal}}
  network: ${DOCKER_NETWORK:algo_space}
worker:
  imageName: ${WORKER_IMAGE:algo-space-worker:1.0}
