springdoc:
  api-docs:
    path: /api-documentation
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:algo_space}
    username: ${MYSQL_USERNAME:algo_space}
    password: ${MYSQL_PASSWORD:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files: sql/tasks.sql,sql/hints.sql,sql/tests.sql,sql/tasks_available_languages.sql
logging:
  level:
    root: debug
allowed:
  origin: ${FRONTEND_IP:http://localhost:3000}
